from typing import Dict, Any, List
from typing_extensions import TypedDict
from langgraph.graph import StateGraph, START, END
from recommender import generate_recommendation
import re

# 1. Define the Graph State
# This represents the data that flows through the graph nodes
class AgentState(TypedDict):
    query: str
    intent: str
    result: str
    product_ids: List[int]

# 2. Define the Nodes
# Each node is a Python function that takes the state, does some work, and returns state updates

def intent_classifier_node(state: AgentState) -> Dict:
    """Classifies the user query intent to route it properly."""
    query_lower = state["query"].lower()
    
    # Simple rule-based intent classification for demo
    support_keywords = ["order", "track", "help", "return", "refund", "broken", "lost", "where is", "şikayet", "iade", "kargo", "nerede", "durumu"]
    
    intent = "recommend" # Default intent
    if any(keyword in query_lower for keyword in support_keywords):
        intent = "support"
        
    print(f"👉 [LangGraph Node: Classifier] Classified intent as: {intent}")
    return {"intent": intent}

def product_recommendation_node(state: AgentState) -> Dict:
    """Node that handles product recommendations by sending it to our Smart Engine (or CrewAI)."""
    print("👉 [LangGraph Node: Recommendation] Routing to Smart Recommender / CrewAI...")
    
    # We use our smart recommender here. In a "live" mode, this could call kickoff_crew()
    rec = generate_recommendation(state["query"])
    
    return {
        "result": rec["result"],
        "product_ids": rec["recommended_product_ids"]
    }

def customer_support_node(state: AgentState) -> Dict:
    """Node that handles customer support queries dynamically based on the input."""
    print("👉 [LangGraph Node: Support] Context-aware routing active...")
    query = state["query"].lower()
    ticket_id = "SB-" + "".join([str(ord(c) % 10) for c in query[:3]]) + "-2024"
    
    # 1. Shipping / Tracking Intent
    if any(k in query for k in ["order", "track", "where", "kargo", "nerede", "durumu"]):
        response = f"""## 📦 Support: Tracking Information
Your query regarding **order tracking** was caught by the LangGraph Support Node.

**Status:** Your most recent order is currently **In Transit**.
**Tracking ID:** `TRK772920193`
**Estimated Delivery:** 2 Business Days.

*Note: You can follow your live shipment on our tracking page.*
\n---\n**Support Ticket Created:** `{ticket_id}`"""

    # 2. Returns / Refunds Intent
    elif any(k in query for k in ["return", "refund", "iade", "iptal"]):
        response = f"""## 🔄 Support: Returns & Refunds
I've routed your request to our **Automated Refund Specialist**.

Our standard policy allows returns within **30 days** of purchase. 
1. Log in to your account.
2. Go to 'Order History'.
3. Click 'Return Item' next to your product.

*We will provide a free shipping label for all eligible returns.*
\n---\n**Support Ticket Created:** `{ticket_id}`"""

    # 3. Damage / Broken / Warranty Intent
    elif any(k in query for k in ["broken", "lost", "damage", "şikayet", "bozuk", "çalışmıyor"]):
        response = f"""## 🛠️ Support: Warranty & Repairs
We are sorry to hear about the issue with your product.

As part of the **SmartBasket Warranty**, your device is covered for 2 years. 
Please provide a photo of the issue so we can initiate a **Free Replacement** process.

*A support specialist will contact you via email within 4 hours.*
\n---\n**Support Ticket Created:** `{ticket_id}`"""

    # 4. General Support / Help
    else:
        response = f"""## 🛠️ General Support
I understand you need assistance. I've routed your query to our general Help Desk.

Please let us know how we can help you today regarding our products or your shopping experience.

\n---\n**Support Ticket Created:** `{ticket_id}`"""

    # Append the LangGraph identifier
    response += "\n\n*(This dynamic response is generated by the updated LangGraph Support Node!)*"
    
    return {
        "result": response,
        "product_ids": []
    }

# 3. Define the Router Logic
def route_by_intent(state: AgentState) -> str:
    """Conditional edge logic that determines the next node based on intent."""
    if state["intent"] == "support":
        return "support"
    return "recommend"

# 4. Build the Graph
print("🔧 Initializing SmartBasket LangGraph...")
workflow = StateGraph(AgentState)

# Add nodes
workflow.add_node("classifier", intent_classifier_node)
workflow.add_node("crewai_recommender", product_recommendation_node)
workflow.add_node("customer_support", customer_support_node)

# Add edges between nodes
workflow.add_edge(START, "classifier")

# Add conditional edges from the classifier
workflow.add_conditional_edges(
    "classifier",
    route_by_intent,
    {
        "recommend": "crewai_recommender",
        "support": "customer_support"
    }
)

# Both endpoints lead to END
workflow.add_edge("crewai_recommender", END)
workflow.add_edge("customer_support", END)

# Compile the graph
smart_router_app = workflow.compile()

def run_graph(query: str) -> dict:
    """Helper method to run the LangGraph application."""
    initial_state = {"query": query, "intent": "", "result": "", "product_ids": []}
    
    # Run the graph
    # LangSmith will automatically trace this if LANGCHAIN_TRACING_V2=true
    final_state = smart_router_app.invoke(initial_state)
    
    return {
        "result": final_state["result"],
        "recommended_product_ids": final_state["product_ids"],
        "intent_detected": final_state["intent"]
    }

if __name__ == "__main__":
    # Test the graph locally
    print("\n--- TEST: Recommend ---")
    print(run_graph("I need a nice watch"))
    
    print("\n--- TEST: Support ---")
    print(run_graph("Where is my order?"))
